CREATE TABLE global_roles
(
    global_role_id bigint GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_GlobalRoles PRIMARY KEY,
    name           varchar(255) NOT NULL
        CONSTRAINT UK_GlobalRoles_name UNIQUE
);

CREATE TABLE users
(
    user_id           bigint GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_Users PRIMARY KEY,
    email             varchar(255) NOT NULL
        CONSTRAINT UK_Users_email UNIQUE,
    login             varchar(255) NOT NULL
        CONSTRAINT UK_Users_login UNIQUE,
    registration_date date         NOT NULL
);

CREATE TABLE user_global_roles
(
    user_id        bigint NOT NULL
        CONSTRAINT FK_UserGlobalRoles_Users REFERENCES users,
    global_role_id bigint NOT NULL
        CONSTRAINT FK_UserGlobalRoles_GlobalRoles REFERENCES global_roles,
    CONSTRAINT PK_UserGlobalRoles PRIMARY KEY (user_id, global_role_id)
);

CREATE TABLE user_passwords
(
    user_password_id bigint GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_UserPasswords PRIMARY KEY,
    password_hash    varchar(255),
    user_user_id     bigint
        CONSTRAINT FK_UserPasswords_Users REFERENCES users
);

