version: "3.9"
services:
  kurento:
    image: kurento/kurento-media-server:latest
    ports:
      - "8888:8888/tcp"
      - "5000-5050:5000-5050/udp"
    environment:
      - KMS_MIN_PORT=5000
      - KMS_MAX_PORT=5050
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017/tcp"
  coturn:
    image: coturn/coturn:latest
    restart: always
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "49160-49200:49160-49200/udp"
    command:
      - "--user=admin:admin"
      - "--TURNSERVER_ENABLED=1"