version: "3.9"
services:
  kurento:
    image: kurento/kurento-media-server:latest
    ports:
      - "8888:8888/tcp"
      - "5000-5050:5000-5050/udp"
    environment:
      - KMS_MIN_PORT=5000
      - KMS_MAX_PORT=5050
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017/tcp"
  backend:
    image: ghcr.io/weldnor/mrc:latest
    depends_on:
      - mongo
      - kurento
    ports:
      - "443:443"
    environment:
      KURENTO_URL: ws://kurento:8888/kurento
      MONGO_HOST: mongo
      SPRING_PROFILES_ACTIVE: prod
  #      KEYSTORE_PASSWORD: ""
  #      KEY_PASSWORD: ""

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"